---

- name: Create certs directory
  file:
    state: directory
    path: "{{ certs_dir }}"
    mode: '0640'
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"

- name: Distribute CA to nodes
  copy:
    src: "{{ local_cert_dir }}/{{ ca_cert_name }}"
    dest: "{{ certs_dir }}/{{ ca_cert_name }}"
    mode: '0640'
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"

- name: Distribute CA key to nodes
  copy:
    src: "{{ local_cert_dir }}/{{ ca_key_name }}"
    dest: "{{ certs_dir }}/{{ ca_key_name }}"
    mode: '0640'
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"