---

- name: Load balancer set up
  hosts: load-balancer
  roles:
    - role: loadbalancer-setup
      when: groups['load-balancer'] | length > 0

- name: Java installation
  hosts: all:!load-balancer
  vars_prompt:
    - name: "cert_password"
      prompt: "Enter cert password"
      private: yes
  roles:
      - role: install-kafka
      - role: certs-generation
      - role: startup-kafka
      - role: metrics-enable
        when: metrics_enabled == "true"



