---

- name: Load balancer set up
  hosts: load-balancer
  roles:
    - loadbalancer-setup
  when: groups['load-balancer'] | length > 0

- name: Generate CA
  hosts: all
  roles:
    - certs-generation
  when: generate_ca == "true"

- name: Java installation
  hosts: all:!load-balancer
  vars_prompt:
    - name: "cert_password"
      prompt: "Enter cert password"
      private: yes
  roles:
    - install-kafka




