---

kafka_version: "3.8.0"
scala_version: "2.13"
kafka_archive: "kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
kafka_url: "https://downloads.apache.org/kafka/{{ kafka_version }}/{{ kafka_archive }}"
truststore_file: "truststore.jks"