---

- name: Kafka installation and base configuration
  include_tasks: kafka.yml

- name: Distribute CA
  include_tasks: distribute_ca.yml

- name: Generate certificates
  include_tasks: generate_certs.yml

- name: Kafka start up
  include_tasks: startup.yml

#- name: Kafka SASL mechanism configuration
#  include_tasks: sasl.yml
#  when: sasl_enabled == "true"

- name: Kafka metrics exporter configuration
  include_tasks: metrics.yml
  when: metrics_enabled == "true"




    
