---

- name: Create admin user
  command:
    cmd: >
      {{ kafka_config_script_path }} --bootstrap-server {{ ansible_host }}:9091 \
        --alter --add-config 'SCRAM-SHA-256=[password={{ kafka_admin_password }}]' \
        --entity-type users --entity-name {{ kafka_admin_name }} \
        --command-config {{ client_properties_path }}
  run_once: true
  
  

# To be continued